---
- name: setup tomcat
  hosts: all
  become: yes
  tasks:
    - name: Install Java RHEL
      yum:
        name: java
        state: installed
      when: ansible_os_family == "RedHat"

    - name: Install Java on Ubuntu
      apt:
        name: default-jdk
        state: present
        update_cache: yes 
      when: ansible_os_family == "Debian"

    - name: Download tomcat packages
      get_url:
        url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.68/bin/apache-tomcat-8.5.68.tar.gz
        dest: /opt
    
    - name: Untar apache packages
      unarchive:
        src: /opt/apache-tomcat-8.5.68.tar.gz
        dest: /opt
        remote_src: True 

    - name: Add execution permission on startup file
      file:
        path: /opt/apache-tomcat-8.5.68/bin/startup.sh
        mode: 0777

    - name: Start the tomacat apache
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-8.5.68/bin
